---

- name: Create keys directory
  file:
    path: /etc/ssl/acme
    state: directory
  register: keys

- name: Generate certificate private key
  openssl_privatekey:
    path: "{{ keys.path }}/private.key"
    size: 4096
    type: RSA

- name: Generate account private key
  openssl_privatekey:
    path: "{{ keys.path }}/letsencrypt.key"
    size: 4096
    type: RSA
